services:
  # Backend Service
  - type: web
    name: ai-resume-builder-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health

  # Frontend Service  
  - type: web
    name: ai-resume-builder-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: ai-resume-builder-backend
          property: host
